development:
  adapter: mysql2
  encoding: utf8  
  database: edu_sns_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: edu_sns_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: edu_sns_production
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true
